server:
  port: 8090
spring:
  application:
    name: barcode-product
  datasource:
    url: jdbc:mysql://172.22.96.53:3306/ctcode?characterEncoding=UTF-8
    username: mes
    password: chenbrosh
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
#mybatis:
#  type-aliases-package: com.chenbro.product.pojo
#  mapper-locations: classpath:mybatis/mappers/**/*.xml    # 配置文件
#feign:
#  hystrix:
feign:
  httpclient:
    connection-timeout: 10000
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms
#    enabled: true