server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
barcode:
  jwt:
    secret: barcode@Login(Auth}*^31)&chenbro% # 登录校验的密钥
    pubKeyPath: D:\\Java\RSA\\rsa.pub # 公钥地址
    priKeyPath: D:\\Java\RSA\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: CB_TOKEN